// Generated by tools/logo.py
window.LOGO = {"w": 1049, "h": 529, "cores": [[351, 292, 25, "#ff4a3d"], [435, 292, 25, "#3f86ff"], [519, 292, 25, "#ffd13a"], [603, 292, 25, "#ff5fae"], [687, 292, 25, "#d9e2ec"]]};
