"""Playable Kharon (1.6.3): assets/source/kharon_player.png, 2 rows x 8 poses ->
assets/sprites/heroes2.png + 'heroes2' entry of js/atlas.js, keys kharon_0..15 in the
same order as the other heroes (see KH_SHEET below)."""
import json, os, re
from PIL import Image
from segment import segment, debug_sheet, ROOT
from build_hd import scaled
from pack import pack

# sheet order: 0 guardia 1-3 passo 4 pugno 5 calcio 6 affondo 7 spada alzata |
#              8 fendente viola 9 colpo dalla mano 10 salto 11 sbalzato 12 a terra 13 presa 14 colpo in presa 15 vittoria
# hero frames: 0 guardia 1-3 passo 4 carica 5 pugno 6 calcio 7 colpito 8 arma su 9 arma giù 10 speciale 11 pistola 12 salto 13 sbalzato 14 a terra 15 vittoria
KH_SHEET = [0, 1, 2, 3, 0, 4, 5, 11, 7, 6, 8, 9, 10, 11, 12, 15]
IDLE_H = 178
atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
fr, _ = segment('kharon_player.png', 2, 8, thr=128, merge_dist=45)
grid = {(f['row'], f['col']): f for f in fr}
assert len(grid) == 16, sorted(grid)
debug_sheet(fr, 8, '/tmp/claude-0/-home-claude/3434d8e8-e296-554c-ac5f-070a00e2bd55/scratchpad/kharon16_dbg.png')
k = IDLE_H / grid[(0, 0)]['img'].height
src = {}
for (r, c), f in grid.items():
    src[r * 8 + c] = scaled(f, k)
frames = [(f'kharon_{i}', *src[s]) for i, s in enumerate(KH_SHEET)]
frames += [('kharon_grab', *src[13]), ('kharon_grabhit', *src[14])]
atlas, meta = pack(frames)
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(os.path.join(ROOT, 'assets', 'sprites', 'heroes2.png'), optimize=True)
META['heroes2'] = meta
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
print('heroes2', atlas.size, len(meta), 'k=%.3f' % k)
exec(open(os.path.join(os.path.dirname(os.path.abspath('build_kharon.py')), 'recolor_kharon.py')).read())
