"""Primal Sentinels II — i titani folk (8 pose ciascuno, griglia 2x4) -> atlanti 'titani' e 'titani2'.
Pose: 0 guardia · 1 passo · 2 colpo veloce · 3 colpo pesante · 4 parata · 5 colpito · 6 colpo finale · 7 a terra
(lo stesso ordine dei fotogrammi 'conc_' di Concordia)."""
import json, os, re
import numpy as np
from PIL import Image
from titan_cut import cut_grid
from build_hd import scaled
from pack import pack
from segment import ROOT

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
# name, file, height of the guard pose on screen (the four-legged ones are lower and longer)
TITANS = {
    'titani': [('leone', 'titano_leone', 470), ('grifone', 'titano_grifone', 400), ('lupa', 'titano_lupa', 370), ('sirena', 'titano_sirena', 470)],
    'titani2': [('toro', 'titano_toro', 480), ('paladino', 'paladino', 480), ('paladinoS', 'paladino_stellare', 490)],
}


def fix(name, g):
    if name == 'paladino_stellare':
        # the energy blade of the thrust pose spills into the next cell
        f = g[(0, 3)]; a = np.array(f['img'])
        blue = (a[..., 2].astype(int) > a[..., 0].astype(int) + 60)
        zone = np.zeros(blue.shape, bool); zone[190:300, :46] = True
        a[blue & zone] = 0
        f['img'] = Image.fromarray(a)
    return g


for sheet, lst in TITANS.items():
    frames = []
    for key, fn, hgt in lst:
        g = fix(fn, cut_grid(fn + '.png'))
        k = hgt / g[(0, 0)]['bh']
        for (r, c), f in sorted(g.items()):
            im, ax, ay = scaled(f, k)
            frames.append((f'{key}_{r * 4 + c}', im, ax, ay))
    atlas, meta = pack(frames)
    out = atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
    out.convert('RGBA').save(os.path.join(ROOT, 'assets', 'sprites', sheet + '.webp'), 'WEBP', lossless=True, method=4)   # webp: the full ZIP must stay under 30 MB
    META[sheet] = meta
    print(sheet, atlas.size, len(meta), os.path.getsize(os.path.join(ROOT, 'assets', 'sprites', sheet + '.webp')) // 1024, 'KB')

open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
