"""Boss pose sheets (1.6.2): assets/source/pose_<boss>.png, 2 rows x 4 poses:
0 guardia · 1 passo · 2 carica · 3 attacco · 4 speciale · 5 colpito · 6 a terra · 7 in ginocchio.
Output: assets/sprites/bosses2.png + the 'bosses2' entry of js/atlas.js (keys <boss>P_0..7).
Each boss keeps the on-screen size of its old sprite (idle height = old <boss>_0 height)."""
import json, os, re
from PIL import Image
from segment import segment, debug_sheet, ROOT
from build_hd import scaled
from pack import pack

BOSSES = ['centipede', 'trivor', 'mimesi', 'kharon', 'custode', 'vespera']
atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
src = open(atlas_js).read()
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', src, re.S).group(1))
frames = []
for b in BOSSES:
    fr, cuts = segment(f'pose_{b}.png', 2, 4, thr=128, merge_dist=70)
    grid = {(f['row'], f['col']): f for f in fr}
    assert len(grid) == 8, (b, sorted(grid))
    old_h = META['bosses'][f'{b}_0'][3]
    k = old_h / grid[(0, 0)]['img'].height
    debug_sheet(fr, 4, f'/tmp/claude-0/-home-claude/3434d8e8-e296-554c-ac5f-070a00e2bd55/scratchpad/pose_{b}_dbg.png')
    for (r, c), f in sorted(grid.items()):
        im, ax, ay = scaled(f, k)
        frames.append((f'{b}P_{r * 4 + c}', im, ax, ay))
    print(b, 'k=%.3f' % k)
atlas, meta = pack(frames)
out = os.path.join(ROOT, 'assets', 'sprites', 'bosses2.png')
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(out, optimize=True)
META['bosses2'] = meta
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
print('bosses2', atlas.size, len(meta))
