import json, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
from PIL import Image
from pack import pack
import items, people
exec(open('build_sheets.py').read())
import build_hd
hd = build_hd.item_frames()
hd_keys = {k for k, *_ in hd}
fr = [f for f in items.build() if f[0] not in hd_keys] + hd
atlas, meta = pack(fr); atlas.save(OUT + 'items.png', optimize=True); META['items'] = meta
import build_hd2
fr = build_hd2.giants_frames()
atlas, meta = pack(fr); atlas.save(OUT + 'giants.png', optimize=True); META['giants'] = meta; print('giants', atlas.size, len(meta))
soldier_h = META['fighters']['soldier_0'][3]
fr = build_hd2.enemy_frames(soldier_h) + build_hd2.prop_frames() + build_hd2.portrait_frames()
atlas, meta = pack(fr); atlas.save(OUT + 'extra.png', optimize=True); META['extra'] = meta; print('extra', atlas.size, len(meta))
fr = build_hd.people_frames()
atlas, meta = pack(fr); atlas.save(OUT + 'people.png', optimize=True); META['people'] = meta
print('items', len(META['items']), 'people', len(META['people']))
src = Image.open(os.path.join(ROOT, 'assets', 'source', 'story.png')).convert('RGB')
for i, n in enumerate(['story_port', 'story_vespera', 'story_cores', 'story_heroes']):
    if n != 'story_cores':
        continue  # only the chamber of the cores is used by the cinematics
    src.crop(((i % 2) * 887, (i // 2) * 444, (i % 2) * 887 + 887, (i // 2) * 444 + 443)).save(os.path.join(ROOT, 'assets', 'bg', n + '.jpg'), quality=90)
js = '// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n'
open(os.path.join(ROOT, 'js', 'atlas.js'), 'w').write(js)
print(len(js))

# shrink the atlases: 256-colour palette (pixel art survives it very well)
for n in os.listdir(OUT):
    if n.endswith('.png'):
        im = Image.open(OUT + n).convert('RGBA')
        im.quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(OUT + n, optimize=True)
print('quantized')

# boss pose sheets (1.6.2) go in their own atlas
exec(open('build_boss_poses.py').read())
exec(open('build_kharon.py').read())
exec(open('build_mentors.py').read())
# 1.8: drago verde, scooter, emblemi, prese, fondale della base
exec(open('build_v18.py').read())
exec(open('build_v19.py').read())
exec(open('build_v111.py').read())
