"""1.11: il convoglio del capitolo 2 (convoglio.png: vagone, vagone aperto, locomotiva) → atlante 'train'.
I pezzi sono uniti dai ganci: si tagliano nelle colonne più vuote tra un pezzo e l'altro."""
import json, os, re
import numpy as np
from PIL import Image
from segment import ROOT
from pack import pack
atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
im = Image.open(os.path.join(ROOT, 'assets', 'source', 'convoglio.png')).convert('RGBA')
a = np.array(im); al = a[..., 3] > 100; col = al.sum(0)
W0 = im.width
c1 = int(W0 * 0.30) + int(np.argmin(col[int(W0 * 0.30):int(W0 * 0.36)]))
c2 = int(W0 * 0.61) + int(np.argmin(col[int(W0 * 0.61):int(W0 * 0.68)]))
frames = []
pieces = [('wagon', 0, c1), ('wagon_open', c1, c2), ('loco', c2, W0)]
# wheels bottom: lowest opaque row of the first wagon = the rail line
ys = np.where(al[:, :c1].any(1))[0]; floor = ys.max()
wag_h = floor - np.where(al[:, 40:c1 - 40].any(1))[0].min()
k = 230 / wag_h
for name, x0, x1 in pieces:
    part = im.crop((x0, 0, x1, im.height))
    bb = part.getbbox(); part = part.crop(bb)
    w, h = round(part.width * k), round(part.height * k)
    part = part.resize((w, h), Image.LANCZOS)
    # anchor: left edge, rail line
    frames.append((name, part, 0, (floor - bb[1]) * k))
atlas, meta = pack(frames)
atlas.save(os.path.join(ROOT, 'assets', 'sprites', 'train.png'), optimize=True)
META['train'] = meta
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
print(c1, c2, meta)
