"""Argo (the Guardian of the Hearts) and Sette (the robot assistant), 1.6.6.
assets/source/argo.png and sette.png, 2 rows x 4 -> assets/sprites/mentors.png, 'mentors' in js/atlas.js.
argo: 0 sereno 1 parla 2 occhi che brillano 3 severo 4 sorride 5 svanisce 6 colonna vuota 7 primo piano
sette: 0 fermo 1 cammina 2 parla 3 panico 4 indica 5 saluta 6 console 7 salta di gioia"""
import json, os, re
from PIL import Image
from segment import segment, debug_sheet, ROOT
from build_hd import scaled
from pack import pack

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
frames = []
for name, target in (('argo', 380), ('sette', 150)):
    fr, _ = segment(f'{name}.png', 2, 4, thr=128, merge_dist=40)
    grid = {(f['row'], f['col']): f for f in fr}
    assert len(grid) == 8, (name, sorted(grid))
    debug_sheet(fr, 4, f'/tmp/claude-0/-home-claude/3434d8e8-e296-554c-ac5f-070a00e2bd55/scratchpad/{name}_dbg.png')
    k = target / grid[(0, 0)]['img'].height
    for (r, c), f in sorted(grid.items()):
        im, ax, ay = scaled(f, k)
        frames.append((f'{name}_{r * 4 + c}', im, ax, ay))
atlas, meta = pack(frames)
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(os.path.join(ROOT, 'assets', 'sprites', 'mentors.png'), optimize=True)
META['mentors'] = meta
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
print('mentors', atlas.size, {k: v[2:4] for k, v in meta.items()})
