"""Gli oggetti HD (tavola 4x5, uguale per PS1 e PS2) -> sostituiscono quelli dell'atlante 'items'.
Le armi personali (w_*) e le assi del treno restano quelle di prima."""
import json, os, re
import numpy as np
from PIL import Image
from titan_cut import cut_grid
from build_hd import scaled
from pack import pack
from segment import ROOT

KEYS = ['pizza', 'chicken', 'can', 'energy', 'coin', 'gem', 'ammo', 'sigil', 'pipe', 'oar',
        'crate', 'bin', 'barrel', 'arancino', 'cannolo', 'coffee', 'gelato', 'star', 'chip', 'anchor']
NEW_SIZE = {'arancino': 52, 'cannolo': 70, 'coffee': 50, 'gelato': 58, 'star': 54, 'chip': 52, 'anchor': 96}
atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
old = META['items']
src = Image.open(os.path.join(ROOT, 'assets', 'sprites', 'items.png')).convert('RGBA')
frames = []
for k, (x, y, w, h, ax, ay) in old.items():
    if k not in KEYS: frames.append((k, src.crop((x, y, x + w, y + h)), ax, ay))
g = cut_grid('oggetti.png', 4, 5, merge=25, wmin=180, wmax=420)
for (r, c), f in sorted(g.items()):
    k = KEYS[r * 5 + c]
    im = f['img']
    if k in old:
        target = max(old[k][2], old[k][3])
    else:
        target = NEW_SIZE[k]
    s = target / max(im.width, im.height)
    im, _, _ = scaled({'img': im, 'ax': 0, 'ay': 0}, s)
    frames.append((k, im, im.width / 2, im.height))
atlas, meta = pack(frames)
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(os.path.join(ROOT, 'assets', 'sprites', 'items.png'), optimize=True)
META['items'] = meta
print('items', atlas.size, len(meta))
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
