"""Primal Sentinels II — ritratti dei dialoghi (2x4) -> atlante 'ritratti2'.
Riga 1: Rigel, Magnar, Sirio mentore, Ciusky Stella · riga 2: Beps, Kathy, Kiki, Don Stella."""
import json, os, re
from PIL import Image
from titan_cut import cut_grid
from build_hd import scaled
from pack import pack
from segment import ROOT

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
KEYS = ['rt_rigel', 'rt_magnar', 'rt_sirio', 'rt_ignisS', 'rt_azurS', 'rt_lyraS', 'rt_auraS', 'rt_onyxS']
g = cut_grid('ritratti_ii.png', 2, 4, merge=20, wmin=330, wmax=520)
frames = []
for (r, c), f in sorted(g.items()):
    k = 230 / f['img'].height
    im, ax, ay = scaled(f, k)
    frames.append((KEYS[r * 4 + c], im, im.width / 2, im.height))
atlas, meta = pack(frames)
p = os.path.join(ROOT, 'assets', 'sprites', 'ritratti2.png')
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(p, optimize=True)
META['ritratti2'] = meta
print('ritratti2', atlas.size, os.path.getsize(p) // 1024, 'KB', {k: v[2:4] for k, v in meta.items()})
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
