"""1.8: tavole generate dall'utente → atlanti 'extra2' (drago verde, scooter col pilota, emblemi) e 'grabs'
(prese dei Sentinels senza il nemico), più il fondale della base (assets/bg/base.jpg)."""
import json, os, re
from PIL import Image
from segment import segment, debug_sheet, ROOT
from build_hd import scaled
from pack import pack

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
DBG = '/tmp/claude-0/-home-claude/3434d8e8-e296-554c-ac5f-070a00e2bd55/scratchpad/'

def grid(name, rows, cols, **kw):
    fr, _ = segment(name, rows, cols, **kw)
    g = {(f['row'], f['col']): f for f in fr}
    debug_sheet(fr, cols, DBG + name.replace('.png', '_dbg.png'))
    assert len(g) == rows * cols, (name, sorted(g))
    return [g[(r, c)] for r in range(rows) for c in range(cols)]

def add(frames, names, fr, k):
    for n, f in zip(names, fr):
        im, ax, ay = scaled(f, k)
        frames.append((n, im, ax, ay))

extra = []
fr = grid('titano_drago.png', 2, 2, thr=128, merge_dist=60)
add(extra, ['beast_dragon_sleep', 'beast_dragon_wake', 'beast_dragon_run', 'beast_dragon_roar'], fr, 240 / fr[3]['img'].height)
fr = grid('scooter.png', 2, 2, thr=128, merge_dist=90)
add(extra, [f'scooter_{i}' for i in range(4)], fr, 165 / fr[0]['img'].height)
fr = grid('emblemi.png', 2, 3, thr=128, merge_dist=30)
add(extra, [f'emblem_{i}' for i in range(6)], fr, 200 / fr[0]['img'].height)
atlas, meta = pack(extra)
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(os.path.join(ROOT, 'assets', 'sprites', 'extra2.png'), optimize=True)
META['extra2'] = meta

grabs = []
for hero in ['ignis', 'azur', 'lyra', 'aura', 'onyx', 'kharon']:
    fr = grid(f'presa_{hero}.png', 2, 2, thr=128, merge_dist=50)
    ref = META['heroes2' if hero == 'kharon' else 'fighters'][f'{hero}_0'][3]
    add(grabs, [f'{hero}_g{i}' for i in range(4)], fr, ref / fr[1]['img'].height)
atlas, meta = pack(grabs)
atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(os.path.join(ROOT, 'assets', 'sprites', 'grabs.png'), optimize=True)
META['grabs'] = meta
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')

bg = Image.open(os.path.join(ROOT, 'assets', 'source', 'base.png')).convert('RGB')
bg.resize((1600, round(1600 * bg.height / bg.width)), Image.LANCZOS).save(os.path.join(ROOT, 'assets', 'bg', 'base.jpg'), quality=88)
print('extra2', META['extra2'].keys().__len__(), 'grabs', len(META['grabs']))
print({k: v[2:4] for k, v in META['extra2'].items()})
print({k: v[2:4] for k, v in META['grabs'].items() if k.endswith('g1') or k.endswith('g0')})
