"""1.9.2: volti frontali ('faces': face_0..5) e pose di presentazione ('poses': <eroe>_p0 attesa, _p1 presentazione, _p2 scelto)."""
import json, os, re
from PIL import Image
from segment import segment, debug_sheet, ROOT
from build_hd import scaled
from pack import pack

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
DBG = '/tmp/claude-0/-home-claude/3434d8e8-e296-554c-ac5f-070a00e2bd55/scratchpad/'
def grid(name, rows, cols, **kw):
    fr, _ = segment(name, rows, cols, **kw)
    g = {(f['row'], f['col']): f for f in fr}
    debug_sheet(fr, cols, DBG + name.replace('.png', '_dbg.png'))
    assert len(g) == rows * cols, (name, sorted(g))
    return [g[(r, c)] for r in range(rows) for c in range(cols)]
def save(frames, name):
    atlas, meta = pack(frames)
    atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(os.path.join(ROOT, 'assets', 'sprites', name + '.png'), optimize=True)
    META[name] = meta

frames = []
fr = grid('volti.png', 2, 3, thr=128, merge_dist=40)
k = 240 / max(f['img'].height for f in fr)
for i, f in enumerate(fr):
    im, ax, ay = scaled(f, k); frames.append((f'face_{i}', im, ax, ay))
save(frames, 'faces')

frames = []
for hero in ['ignis', 'azur', 'lyra', 'aura', 'onyx', 'kharon']:
    fr = grid(f'posa_{hero}.png', 1, 3, thr=128, merge_dist=70)
    ref = META['heroes2' if hero == 'kharon' else 'fighters'][f'{hero}_0'][3] * 1.08
    # scale on the body height of the waiting pose (weapons excluded as far as possible: use the boots-to-head of pose 0)
    k = ref / fr[0]['img'].height
    for i, f in enumerate(fr):
        im, ax, ay = scaled(f, k); frames.append((f'{hero}_p{i}', im, ax, ay))
save(frames, 'poses')
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
print({k: v[2:4] for k, v in META['faces'].items()})
print({k: v[2:4] for k, v in META['poses'].items()})
