"""Primal Sentinels II — le Sentinelle nell'armatura Cuori di Stella (tavole 2x8) -> atlante 'stella2'.
Le tavole generate hanno un ordine diverso da quello del gioco: qui lo rimappo.
Ordine della tavola: 0 guardia · 1-3 camminata · 4 pugno · 5 calcio · 6 carica l'arma · 7 colpo d'arma ·
8 speciale a spirale · 9 speciale con lo spirito del titano · 10 sparo · 11 salto · 12 braccia avanti ·
13 colpito · 14 a terra · 15 vittoria."""
import json, os, re
from PIL import Image
from titan_cut import cut_grid
from build_hd import scaled
from pack import pack
from segment import ROOT

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
# the figures touch each other: column cuts chosen by eye on each sheet (row 1, row 2)
SHEETS = {
    'ignis': ('stella_ciusky', [(255, 490, 720, 925, 1235, 1535, 1775), (300, 675, 990, 1180, 1475, 1645, 1955)]),
    'azur': ('stella_beps', [(260, 520, 765, 990, 1245, 1525, 1748), (330, 595, 945, 1150, 1430, 1640, 1965)]),
    'lyra': ('stella_kathy', [(240, 480, 740, 962, 1280, 1505, 1795), (320, 690, 1020, 1175, 1450, 1660, 1965)]),
    'aura': ('stella_kiki', [(240, 470, 695, 925, 1210, 1495, 1760), (375, 745, 1010, 1240, 1480, 1685, 1990)]),
    'onyx': ('stella_don', [(245, 460, 685, 910, 1205, 1500, 1772), (255, 650, 950, 1170, 1410, 1670, 1975)]),
}
# game pose -> sheet pose (game: 0 guardia 1-3 passo 4 accovacciato 5 pugno 6 calcio volante 7 colpito
# 8 carica 9 colpo d'arma 10 speciale 11 sparo 12 salto 13 sbalzato 14 a terra 15 presa)
GAME = [0, 1, 2, 3, 12, 4, 5, 13, 6, 7, 9, 10, 11, 13, 14, 12]

frames = []
for hid, (fn, cuts) in SHEETS.items():
    g = cut_grid(fn + '.png', 2, 8, xcuts=cuts)
    k = 168 / g[(0, 0)]['bh']
    src = {r * 8 + c: scaled(f, k) for (r, c), f in g.items()}
    for gi, si in enumerate(GAME):
        frames.append((f'{hid}S_{gi}', *src[si]))
    frames.append((f'{hid}S_v', *src[15]))     # victory
    frames.append((f'{hid}S_sw', *src[8]))     # spinning special
atlas, meta = pack(frames)
out = atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
p = os.path.join(ROOT, 'assets', 'sprites', 'stella2.png'); out.save(p, optimize=True)
META['stella2'] = meta
print('stella2', atlas.size, len(meta), os.path.getsize(p) // 1024, 'KB')
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
