"""Primal Sentinels II — i cinque ragazzi in borghese che lottano (cap. 3 'Senza armatura') -> atlante 'borghese'.
Tavola con scritte: 5 righe (Ciusky, Beps, Kathy, Kiki, Don) x 8 pose:
0 guardia · 1 pugno · 2 calcio · 3 colpito · 4 salto · 5 a terra · 6 con tubo · 7 colpo col tubo."""
import json, os, re
import numpy as np
from PIL import Image
from scipy import ndimage as ndi
from build_hd import scaled
from pack import pack
from segment import ROOT, SRC

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
BANDS = [(0, 141), (162, 298), (324, 459), (486, 621), (642, 770)]    # the figures, without the captions under them
IDS = ['ignis', 'azur', 'lyra', 'aura', 'onyx']
rgba = np.array(Image.open(SRC + 'borghese_lotta.png').convert('RGBA'))
frames = []
for hid, (y0, y1) in zip(IDS, BANDS):
    band = rgba[y0:y1].copy(); band[:, :112] = 0          # drop the name on the left
    m = band[..., 3] > 110
    lab, n = ndi.label(m, structure=np.ones((3, 3)))
    sizes = ndi.sum(m, lab, range(1, n + 1)); objs = ndi.find_objects(lab)
    order = sorted(range(n), key=lambda i: -sizes[i])[:8]
    order.sort(key=lambda i: objs[i][1].start)
    grp = {i: [i] for i in order}
    for i in range(n):
        if i in grp or sizes[i] < 15: continue
        sl = objs[i]; best, bd = None, 1e9
        for b in order:
            o = objs[b]
            dx = max(o[1].start - sl[1].stop, sl[1].start - o[1].stop, 0); dy = max(o[0].start - sl[0].stop, sl[0].start - o[0].stop, 0)
            d = np.hypot(dx, dy)
            if d < bd: best, bd = b, d
        if bd < 40: grp[best].append(i)
    body0 = None
    for k, b in enumerate(order):
        ids = [i + 1 for i in grp[b]]
        ys = [objs[i][0] for i in grp[b]]; xs = [objs[i][1] for i in grp[b]]
        a0, a1 = min(s.start for s in ys), max(s.stop for s in ys); b0, b1 = min(s.start for s in xs), max(s.stop for s in xs)
        crop = band[a0:a1, b0:b1].copy(); keep = np.isin(lab[a0:a1, b0:b1], ids)
        crop[~keep] = 0; crop[keep, 3] = 255
        yy, xx = np.nonzero(lab[a0:a1, b0:b1] == b + 1)
        foot, top = yy.max(), yy.min()
        mid = (yy > top + (foot - top) * 0.25) & (yy < top + (foot - top) * 0.6)
        f = dict(img=Image.fromarray(crop), ax=float(xx[mid].mean()), ay=float(foot + 1))
        if k == 0: body0 = foot - top
        frames.append((f'{hid}B_{k}', *scaled(f, 146 / body0)))
atlas, meta = pack(frames)
out = atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
p = os.path.join(ROOT, 'assets', 'sprites', 'borghese.png'); out.save(p, optimize=True)
META['borghese'] = meta
print('borghese', atlas.size, len(meta), os.path.getsize(p) // 1024, 'KB')
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
