"""Primal Sentinels II — primo blocco di tavole (capitoli 1-3) -> atlanti.
  rigel.png            4x4  -> 'rigel'   rigel_0..15 (pose da eroe) + rigelP_0..7 (pose da boss)
  soldati_ferrea.png   2x6  -> 'ferrea'  fante_*, bruto_*
  generale_ferro.png   2x4  -> 'ferrea'  generaleP_0..7 (formato boss a 8 pose)
  capsula.png          1x1  -> 'ferrea'  capsula
  magnar.png           1x5  -> 'ferreaG' magnarG_0..4
  astrale.png          2x3  -> 'ferreaG' astrale_0..5
  cuori_di_stella_design.png 1x5 -> 'stella' stella_0..4
  bg_festa.png         -> assets/bg/festa.jpg
Tutte le figure del gioco guardano a DESTRA: le tavole girate a sinistra vengono specchiate."""
import json, os, re
from PIL import Image, ImageOps
from segment import segment, debug_sheet, ROOT, SRC
from build_hd import scaled
from pack import pack

DBG = '/tmp/claude-0/-home-claude/3434d8e8-e296-554c-ac5f-070a00e2bd55/scratchpad/'
atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))


def grid_of(name, rows, cols, **kw):
    fr, _ = segment(name, rows, cols, **kw)
    g = {(f['row'], f['col']): f for f in fr}
    miss = [(r, c) for r in range(rows) for c in range(cols) if (r, c) not in g]
    if miss: print('WARNING', name, 'missing', miss)
    debug_sheet(fr, cols, DBG + 'dbg_' + name)
    return g


def fit(f, k, flip=False):
    im, ax, ay = scaled(f, k)
    if flip:
        im = ImageOps.mirror(im); ax = im.width - ax
    return im, ax, ay


def save(sheet, frames, quant=True):
    atlas, meta = pack(frames)
    out = atlas.convert('RGBA')
    if quant: out = out.quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
    out.save(os.path.join(ROOT, 'assets', 'sprites', sheet + '.png'), optimize=True)
    META[sheet] = meta
    print(sheet, atlas.size, len(meta))


# ---- Rigel: 16 hero poses in the same order as the other Sentinels
g = grid_of('rigel.png', 4, 4, thr=128, merge_dist=60)
k = 178 / g[(0, 0)]['img'].height
src = {r * 4 + c: fit(f, k) for (r, c), f in g.items()}
frames = [(f'rigel_{i}', *src[i]) for i in range(16)]
# boss layout: 0 guardia 1 passo 2 carica 3 attacco 4 speciale 5 colpito 6 a terra 7 in ginocchio
for i, s in enumerate([0, 2, 8, 9, 10, 7, 14, 4]):
    frames.append((f'rigelP_{i}', *src[s]))
save('rigel', frames)

# ---- Ferrea: foot soldiers, the general, the capsule
ferrea = []
g = grid_of('soldati_ferrea.png', 2, 6, thr=128, merge_dist=50)
k1 = 165 / g[(0, 0)]['img'].height
k2 = 1.35 * 165 / g[(0, 0)]['img'].height          # the brute is bigger than the spearman
for row, pre, kk in ((0, 'fante', k1), (1, 'bruto', k2)):
    s = {c: fit(g[(row, c)], kk, flip=True) for c in range(6)}
    # enemy layout: 0 fermo · 1-2 passo · 3 carica · 4 attacco · 5 colpito · down
    for i, c in enumerate([0, 1, 2, 2, 3, 4]):
        ferrea.append((f'{pre}_{i}', *s[c]))
    ferrea.append((f'{pre}_down', *s[5]))
g = grid_of('generale_ferro.png', 2, 4, thr=128, merge_dist=60)
k = 200 / g[(0, 0)]['img'].height
s = {r * 4 + c: fit(f, k, flip=True) for (r, c), f in g.items()}
# sheet: 0 fermo 1 passo 2 carica 3 schianto 4 colpito 5 senza armatura 6 ruggito 7 in ginocchio
for i, c in enumerate([0, 1, 2, 3, 6, 4, 7, 5]):
    ferrea.append((f'generaleP_{i}', *s[c]))
cap = Image.open(SRC + 'capsula.png').convert('RGBA'); cap = cap.crop(cap.getbbox())
kc = 240 / cap.width
cap = cap.resize((round(cap.width * kc), round(cap.height * kc)), Image.LANCZOS)
ferrea.append(('capsula', cap, cap.width / 2, cap.height - 6))
save('ferrea', ferrea)

# ---- giants: Magnar and Astrale
big = []
g = grid_of('magnar.png', 1, 5, thr=128, merge_dist=70)
k = 440 / g[(0, 0)]['img'].height
for c in range(5): big.append((f'magnarG_{c}', *fit(g[(0, c)], k, flip=True)))
g = grid_of('astrale.png', 2, 3, thr=128, merge_dist=70)
k = 430 / g[(0, 2)]['img'].height
for (r, c), f in g.items(): big.append((f'astrale_{r * 3 + c}', *fit(f, k)))
save('ferreaG', big)

# ---- the Cuori di Stella armours (front view, for menus and cinematics)
g = grid_of('cuori_di_stella_design.png', 1, 5, thr=128, merge_dist=40)
k = 330 / g[(0, 0)]['img'].height
save('stella', [(f'stella_{c}', *fit(g[(0, c)], k)) for c in range(5)])

open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')

# ---- background of chapter 1
bg = Image.open(SRC + 'bg_festa.png').convert('RGB')
bg = bg.resize((round(bg.width * 724 / bg.height), 724), Image.LANCZOS)
bg.save(os.path.join(ROOT, 'assets', 'bg', 'festa.jpg'), quality=88)
print('festa', bg.size)
