"""Primal Sentinels II — mostri giganti (1x5) e boss dei capitoli (2x4) -> atlanti 'mostri' e 'boss2'.
Mostri: 0 fermo · 1 carica · 2 colpo · 3 colpito · 4 sconfitto (tavole rivolte a sinistra: specchiate).
Boss: 0 fermo · 1 passo · 2 carica · 3 attacco · 4 speciale · 5 colpito · 6 a terra · 7 in ginocchio."""
import json, os, re, sys
from PIL import Image, ImageOps
from titan_cut import cut_grid
from build_hd import scaled
from pack import pack
from segment import ROOT

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
PREVIEW = len(sys.argv) > 1


def fit(f, k, flip):
    im, ax, ay = scaled(f, k)
    if flip: im = ImageOps.mirror(im); ax = im.width - ax
    return im, ax, ay


def save(sheet, frames):
    atlas, meta = pack(frames)
    out = atlas.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
    p = os.path.join(ROOT, 'assets', 'sprites', sheet + '.png'); out.save(p, optimize=True)
    META[sheet] = meta
    print(sheet, atlas.size, len(meta), os.path.getsize(p) // 1024, 'KB')


# key, file, height of pose 0 on screen, facing left in the sheet?
MONSTERS = [('idra', 'mostro_idra', 430), ('colosso', 'mostro_colosso', 450), ('vuotoM', 'mostro_vuoto', 460),
            ('tirannoC', 'mostro_tiranno_catene', 440), ('re', 'mostro_re_vuoto', 500)]
BOSSES = [('centurione', 'boss_centurione', 205), ('fabbro', 'boss_fabbro', 215), ('guardia', 'boss_guardia_re', 225),
          ('vesperav', 'boss_vespera_vuoto', 215)]
frames = []
for key, fn, h in MONSTERS:
    g = cut_grid(fn + '.png', 1, 5, wmin=180, wmax=520)
    k = h / g[(0, 0)]['bh']
    for c in range(5): frames.append((f'{key}G_{c}', *fit(g[(0, c)], k, True)))
save('mostri', frames)
frames = []
for key, fn, h in BOSSES:
    g = cut_grid(fn + '.png', 2, 4, wmin=180, wmax=560)
    k = h / g[(0, 0)]['bh']
    for (r, c), f in sorted(g.items()): frames.append((f'{key}P_{r * 4 + c}', *fit(f, k, False)))
save('boss2', frames)
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
