"""Primal Sentinels II — il drone di Ferrea (2x3) -> atlante 'drone2'.
0-1 volo · 2 spara · 3 colpito · 4 cade · 5 a pezzi a terra (rivolto a destra)."""
import json, os, re
from PIL import Image
from titan_cut import cut_grid
from build_hd import scaled
from pack import pack
from segment import ROOT

atlas_js = os.path.join(ROOT, 'js', 'atlas.js')
META = json.loads(re.search(r'window\.ATLAS = (\{.*\});', open(atlas_js).read(), re.S).group(1))
g = cut_grid('drone_ferrea.png', 2, 3, merge=40, xcuts=[(480, 955), (540, 965)])
k = 118 / g[(0, 0)]['bh']
frames = [(f'droneF_{r * 3 + c}', *scaled(f, k)) for (r, c), f in sorted(g.items())]
atlas, meta = pack(frames)
p = os.path.join(ROOT, 'assets', 'sprites', 'drone2.png'); atlas.save(p, optimize=True)
META['drone2'] = meta
print('drone2', atlas.size, os.path.getsize(p) // 1024, 'KB', {k: [round(x) for x in v] for k, v in meta.items()})
open(atlas_js, 'w').write('// Generated by tools/build_all.py — frame = [x, y, w, h, anchorX, anchorY]\nwindow.ATLAS = ' + json.dumps(META, separators=(',', ':')) + ';\n')
